### ISSUE TITLE
convert to localstorage to chrome.storage.sync

### ISSUE THREAD

**Issue by johnsylvain** [johnsylvain/reddit-showerthoughts-newtab#1]
convert to localstorage to [chrome.storage.sync](https://developer.chrome.com/extensions/storage#property-sync) to sync data across devices

**Comment by ypahalajani** [comment]
Hi @johnsylvain,  I am working on it.

**Comment by ypahalajani** [comment]
@johnsylvain : _chrome.storage.sync has limited storage of 100kb and 4kb per object._ I think we need to use client side chrome storage to store such size of data in chrome storage i.e using **chrome.storage.sync** to **chrome.storage.local** . What do u say?

**Comment by ypahalajani** [comment]
I've implemented chrome storage using chrome.storage.local

**Comment by johnsylvain** [comment]
Works for me, wasn't aware of that limitation. Send a PR and I'll review

**Comment by ypahalajani** [comment]
@johnsylvain: today morning when my laptop was not connected to internet, I opened a new tab. And, nothing was being displayed. Seems like, the data is not being stored in chrome storage or chrome.storage.local gets wiped off after I close the chrome browser. This is not what we wanted, right?

**Comment by johnsylvain** [comment]
I refactored the `chrome.storage.local` implementation and the offline functionality is working for me. Try pulling down the most recent commit - if the problem persists I will reopen the issue.

**Comment by ypahalajani** [comment]
@johnsylvain : Indeed - a good use case for promise while getting data from chrome.storage.local. :+1:
